---
title: "Extracirricular Projects"
subtitle: "Portfolio of projects I'm working on in my free time"
---

## [Data analysis for Centenario](https://colab.research.google.com/gist/c-a-s-t-l-e/d1820a1cd153a3eff677b780604fb06e/centenario_mostly_final.ipynb)

This was a project I worked as a project manager on for BYUI Data Science society. We were delivered data from a Mexican car rental company that had been partially cleansed. My primary responsibility was to direct other students by assigning them questions to answer with the data, helping them as they ran into roadblocks. I also contributed by collecting data on different car models' repair intervals.

## [Digit Recognition](https://github.com/Joeljensen28/jensen_ml_projects/blob/main/code/train_test.ipynb)

This project was my first attempt at working with neural networks. Collaborating with my brother, we resolved to build a simple model that could detect handwritten digits using the MNIST dataset, classifying them as 0-9.

## [Baseball Pitch Predictor](https://github.com/PioneerBallMetrics/PBL_Data/blob/main/data/pitch_predictor/model.ipynb)

This was my second attempt at working with neural networks. It was a project I developed for a local baseball team in Idaho Falls which aims to make a prediction on what the next pitch type will be based on the previous five pitches and other conditions that can be recorded pre-pitch. The data was scattered across a few different folders in the repository, so the project began with some wrangling, compiling all the pitch data we had into one single datatable with about 180,000 rows. After that, I removed all features that could not be detected pre-pitch, made the dataset ML-ready, and developed the deep learning model using tools such as tensorflow and kerastuner.

## [Apostle Predictor](https://github.com/Joeljensen28/personal_projects/tree/master/apostle_data)

This is a simpler, more data cleansing-focused personal project I am working on. In my church, if the president passes away, then the apostle with the greatest seniority becomes the next president. I'm aiming to build a machine learning model that can predict whether or not an apostle will ever become president. I started by scraping data from wikipedia on all the Church's apostles, past and present, including their birthday, date ordained into the quorum of the twelve apostles, and whether or not they ever became president. Primarily from the first two, I was able to derive their age at ordination, the age of all _other_ apostles at the date of their ordination, and other critical features helpful for predicting if they will become president.

## [Crash Analysis of Motorcycles in NYC](https://github.com/BYUI335/DS350_SP24_Jensen_Joel/blob/master/week_13/final_project.html.md)

This project is a simple report on a question I had regarding the safety of riding motorcycles. I wanted to learn if it was actually more dangerous to ride a motorcycle, and if so, why. I found a dataset of all reported crashes in the city of New York over the span of several years, along with another dataset of every registered vehicle in NYC. With this, I was able to determine what percentage of motorcyclists actually get in crashes, and how that compares to other types of vehicles.